//Initial implementation of the dashboard javascript generated by chatgpt.
const pageSize = 20;
const tableBody = document.querySelector('#contacts-body');
const searchInput = document.querySelector('#search');
const pageRange = document.querySelector('#page-range');
const statusBar = document.querySelector('#status-bar');
const prevPageBtn = document.querySelector('#prev-page');
const nextPageBtn = document.querySelector('#next-page');
const createBtn = document.querySelector('#create-contact');
const modal = document.querySelector('#contact-modal');
const modalTitle = document.querySelector('#modal-title');
const contactForm = document.querySelector('#contact-form');
const cancelModalBtn = document.querySelector('#cancel-modal');
const deleteModal = document.querySelector('#delete-modal');
const cancelDeleteBtn = document.querySelector('#cancel-delete');
const confirmDeleteBtn = document.querySelector('#confirm-delete');
const logoutBtn = document.querySelector('#logout-btn');
const photoInput = document.querySelector('#photo');
const photoPreview = document.querySelector('#photo-preview');
const removePhotoBtn = document.querySelector('#remove-photo');
const photoStatus = document.querySelector('#photo-status');

let currentPage = 1;
let totalPages = 1;
let currentSearch = '';
let editingContactId = null;
let deleteContactId = null;
let currentPhotoData = '';
const contactsById = new Map();
const maxPhotoFileSize = 5 * 1024 * 1024;
const maxPhotoDataLength = 700000;
const maxPhotoDimension = 256;
const allowedPhotoTypes = ['image/jpeg', 'image/png', 'image/webp'];

const setStatus = (message, isError = false) => {
  statusBar.textContent = message;
  statusBar.classList.toggle('error', isError);
};

const setPhotoStatus = (message, isError = false) => {
  photoStatus.textContent = message;
  photoStatus.classList.toggle('error', isError);
};

const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
}[char]));

const sanitizePhotoData = (photoData) => {
  if (typeof photoData !== 'string' || photoData.length > maxPhotoDataLength) {
    return '';
  }

  return /^data:image\/(?:png|jpe?g|webp);base64,[A-Za-z0-9+/=]+$/i.test(photoData)
    ? photoData
    : '';
};

const getFullName = (contact) => `${contact.firstName || ''} ${contact.lastName || ''}`.trim();

const getInitials = (contact) => {
  const first = (contact.firstName || '').trim().charAt(0);
  const last = (contact.lastName || '').trim().charAt(0);
  return `${first}${last}`.toUpperCase() || '?';
};

const renderAvatarMarkup = (contact) => {
  const photoData = sanitizePhotoData(contact.photoData);
  const fullName = getFullName(contact) || 'Contact';

  if (photoData) {
    return `<img src="${photoData}" alt="${escapeHtml(`${fullName} photo`)}" />`;
  }

  return `<span>${escapeHtml(getInitials(contact))}</span>`;
};

const updatePhotoPreview = () => {
  const previewContact = {
    firstName: contactForm.firstName.value,
    lastName: contactForm.lastName.value,
    photoData: currentPhotoData,
  };

  photoPreview.innerHTML = renderAvatarMarkup(previewContact);
  removePhotoBtn.disabled = !currentPhotoData;
};

const readFileAsDataUrl = (file) => new Promise((resolve, reject) => {
  const reader = new FileReader();
  reader.onload = () => resolve(reader.result);
  reader.onerror = () => reject(new Error('Could not read the selected photo.'));
  reader.readAsDataURL(file);
});

const loadImage = (dataUrl) => new Promise((resolve, reject) => {
  const image = new Image();
  image.onload = () => resolve(image);
  image.onerror = () => reject(new Error('Could not load the selected photo.'));
  image.src = dataUrl;
});

const resizePhoto = async (file) => {
  if (!allowedPhotoTypes.includes(file.type)) {
    throw new Error('Choose a PNG, JPG, or WebP image.');
  }

  if (file.size > maxPhotoFileSize) {
    throw new Error('Choose a photo smaller than 5 MB.');
  }

  const dataUrl = await readFileAsDataUrl(file);
  const image = await loadImage(dataUrl);
  const scale = Math.min(maxPhotoDimension / image.width, maxPhotoDimension / image.height, 1);
  const width = Math.max(1, Math.round(image.width * scale));
  const height = Math.max(1, Math.round(image.height * scale));
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;

  const context = canvas.getContext('2d');
  if (!context) {
    throw new Error('Photo could not be processed.');
  }

  context.fillStyle = '#ffffff';
  context.fillRect(0, 0, width, height);
  context.drawImage(image, 0, 0, width, height);

  const resizedDataUrl = canvas.toDataURL('image/jpeg', 0.84);
  if (resizedDataUrl.length > maxPhotoDataLength) {
    throw new Error('The selected photo is too large.');
  }

  return resizedDataUrl;
};

const renderNotFound = () => {
  document.title = '404 - Not Found';
  document.body.innerHTML = `
    <main style="min-height:100vh;display:flex;align-items:center;justify-content:center;background:#0b263f;color:#fff;text-align:center;padding:24px;">
      <div>
        <h1 style="font-size:48px;margin-bottom:12px;">404</h1>
        <p style="font-size:16px;opacity:0.85;">Page not found.</p>
        <a href="index.html" style="display:inline-block;margin-top:18px;padding:8px 14px;border-radius:4px;background:#9fd3ff;color:#0a2540;text-decoration:none;font-size:12px;font-weight:700;letter-spacing:0.6px;">RETURN TO HOME</a>
      </div>
    </main>
  `;
};

const apiFetch = async (path, options = {}) => {
  const response = await fetch(path, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
    credentials: 'include',
  });

  if (response.status === 401 || response.status === 403) {
    renderNotFound();
    return null;
  }

  return response;
};

const readError = async (response, fallback) => {
  try {
    const data = await response.json();
    return data.error || fallback;
  } catch (error) {
    const message = await response.text();
    return message || fallback;
  }
};

const renderRows = (contacts) => {
  tableBody.innerHTML = '';
  contactsById.clear();

  if (!contacts.length) {
    const row = document.createElement('tr');
    row.innerHTML = '<td colspan="12" class="empty-row">No contacts found.</td>';
    tableBody.appendChild(row);
    return;
  }

  contacts.forEach((contact, index) => {
    const contactId = String(contact.id);
    contactsById.set(contactId, contact);

    const row = document.createElement('tr');
    row.innerHTML = `
      <td>${index + 1}</td>
      <td><div class="contact-avatar">${renderAvatarMarkup(contact)}</div></td>
      <td>${escapeHtml(contact.firstName || '')}</td>
      <td>${escapeHtml(contact.lastName || '')}</td>
      <td>${escapeHtml(contact.email)}</td>
      <td>${escapeHtml(contact.phone)}</td>
      <td>${escapeHtml(contact.address || '')}</td>
      <td>${escapeHtml(contact.city || '')}</td>
      <td>${escapeHtml(contact.state || '')}</td>
      <td>${escapeHtml(contact.zipCode || '')}</td>
      <td>${escapeHtml(contact.notes || '')}</td>
      <td class="actions">
        <button class="icon-btn" data-action="edit" data-id="${escapeHtml(contactId)}" title="Edit" aria-label="Edit">✎ Edit </button>
        <button class="icon-btn" data-action="delete" data-id="${escapeHtml(contactId)}" title="Delete" aria-label="Delete">🗑 Delete </button>
      </td>
    `;
    tableBody.appendChild(row);
  });
};

const updateFooter = (totalContacts) => {
  const start = totalContacts === 0 ? 0 : (currentPage - 1) * pageSize + 1;
  const end = Math.min(currentPage * pageSize, totalContacts);
  pageRange.textContent = `${start}–${end} of ${totalContacts}`;
  prevPageBtn.disabled = currentPage <= 1;
  nextPageBtn.disabled = currentPage >= totalPages;
};

const loadContacts = async () => {
  setStatus('');
  const params = new URLSearchParams({
    search: currentSearch,
    page: String(currentPage),
    pageSize: String(pageSize),
  });

  const response = await apiFetch(`/api/contacts?${params.toString()}`);
  if (!response) {
    return;
  }

  if (!response.ok) {
    if (response.status === 401 || response.status === 403) {
      renderNotFound();
      return;
    }
    const message = await readError(response, 'Failed to load contacts.');
    setStatus(message, true);
    return;
  }

  const contentType = response.headers.get('Content-Type') || '';
  if (!contentType.includes('application/json')) {
    renderNotFound();
    return;
  }

  const data = await response.json();
  renderRows(data.contacts || []);
  totalPages = data.totalPages || 1;
  updateFooter(data.totalContacts || 0);
};

const openModal = (mode, contact = {}) => {
  editingContactId = mode === 'edit' ? contact.id : null;
  modalTitle.textContent = mode === 'edit' ? 'Edit Contact' : 'Create Contact';
  contactForm.firstName.value = contact.firstName || '';
  contactForm.lastName.value = contact.lastName || '';
  contactForm.email.value = contact.email || '';
  contactForm.phone.value = contact.phone || '';
  contactForm.address.value = contact.address || '';
  contactForm.city.value = contact.city || '';
  contactForm.state.value = contact.state || '';
  contactForm.zipCode.value = contact.zipCode || '';
  contactForm.notes.value = contact.notes || '';
  currentPhotoData = sanitizePhotoData(contact.photoData);
  photoInput.value = '';
  setPhotoStatus('');
  updatePhotoPreview();
  modal.classList.add('open');
  modal.setAttribute('aria-hidden', 'false');
};

const closeModal = () => {
  modal.classList.remove('open');
  modal.setAttribute('aria-hidden', 'true');
  contactForm.reset();
  editingContactId = null;
  currentPhotoData = '';
  setPhotoStatus('');
  updatePhotoPreview();
};

const handleSave = async (event) => {
  event.preventDefault();

  const payload = {
    firstName: contactForm.firstName.value.trim(),
    lastName: contactForm.lastName.value.trim(),
    email: contactForm.email.value.trim(),
    phone: contactForm.phone.value.trim(),
    address: contactForm.address.value.trim(),
    city: contactForm.city.value.trim(),
    state: contactForm.state.value.trim(),
    zipCode: contactForm.zipCode.value.trim(),
    notes: contactForm.notes.value.trim(),
    photoData: currentPhotoData,
  };

  const isEditing = Boolean(editingContactId);
  const endpoint = isEditing
    ? `/api/contacts/${editingContactId}`
    : '/api/contacts';
  const method = isEditing ? 'PUT' : 'POST';

  const response = await apiFetch(endpoint, {
    method,
    body: JSON.stringify(payload),
  });

  if (!response) {
    return;
  }

  if (!response.ok) {
    const message = await readError(response, 'Save failed.');
    setStatus(message, true);
    return;
  }

  closeModal();
  await loadContacts();
};

const handleDelete = async (contactId) => {
  const response = await apiFetch(`/api/contacts/${contactId}`, {
    method: 'DELETE',
  });

  if (!response) {
    return;
  }

  if (!response.ok) {
    const message = await readError(response, 'Delete failed.');
    setStatus(message, true);
    return;
  }

  await loadContacts();
};

const openDeleteModal = (contactId, name) => {
  deleteContactId = contactId;
  const text = deleteModal.querySelector('.modal-text');
  text.textContent = name
    ? `Are you sure you want to delete ${name}?`
    : 'Are you sure you want to delete this contact?';
  deleteModal.classList.add('open');
  deleteModal.setAttribute('aria-hidden', 'false');
};

const closeDeleteModal = () => {
  deleteContactId = null;
  deleteModal.classList.remove('open');
  deleteModal.setAttribute('aria-hidden', 'true');
};

let searchTimer;
searchInput.addEventListener('input', (event) => {
  clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    currentSearch = event.target.value.trim();
    currentPage = 1;
    loadContacts();
  }, 300);
});

prevPageBtn.addEventListener('click', () => {
  if (currentPage > 1) {
    currentPage -= 1;
    loadContacts();
  }
});

nextPageBtn.addEventListener('click', () => {
  if (currentPage < totalPages) {
    currentPage += 1;
    loadContacts();
  }
});

createBtn.addEventListener('click', () => openModal('create'));
cancelModalBtn.addEventListener('click', closeModal);
modal.addEventListener('click', (event) => {
  if (event.target === modal) {
    closeModal();
  }
});
cancelDeleteBtn.addEventListener('click', closeDeleteModal);
deleteModal.addEventListener('click', (event) => {
  if (event.target === deleteModal) {
    closeDeleteModal();
  }
});
confirmDeleteBtn.addEventListener('click', async () => {
  if (deleteContactId) {
    await handleDelete(deleteContactId);
  }
  closeDeleteModal();
});

contactForm.addEventListener('submit', handleSave);
contactForm.firstName.addEventListener('input', updatePhotoPreview);
contactForm.lastName.addEventListener('input', updatePhotoPreview);

photoInput.addEventListener('change', async (event) => {
  const [file] = event.target.files;
  if (!file) {
    return;
  }

  const previousPhotoData = currentPhotoData;
  setPhotoStatus('');

  try {
    currentPhotoData = await resizePhoto(file);
    updatePhotoPreview();
  } catch (error) {
    currentPhotoData = previousPhotoData;
    photoInput.value = '';
    updatePhotoPreview();
    setPhotoStatus(error.message || 'Photo could not be added.', true);
  }
});

removePhotoBtn.addEventListener('click', () => {
  currentPhotoData = '';
  photoInput.value = '';
  setPhotoStatus('');
  updatePhotoPreview();
});

tableBody.addEventListener('click', async (event) => {
  const button = event.target.closest('button[data-action]');
  if (!button) {
    return;
  }

  const action = button.dataset.action;
  const contactId = button.dataset.id;

  if (action === 'delete') {
    const contact = contactsById.get(contactId);
    openDeleteModal(contactId, contact ? getFullName(contact) : '');
    return;
  }

  const contact = contactsById.get(contactId);
  if (contact) {
    openModal('edit', contact);
  }
});

document.querySelector('#page-size').textContent = pageSize;
updatePhotoPreview();
loadContacts();

logoutBtn.addEventListener('click', async () => {
  await apiFetch('/api/logout', { method: 'POST' });
  window.location.href = 'login.html';
});
